const PathName = {
  LandingPage: '/',
  Login: '/login',
  Dashboard: '/dashboard',
  Profile: '/profile',
  ForgotPassword: '/forgot-password',
  ResetPassword: '/reset-password',
  ResendEmail: '/resend-email',
  UserManagement: '/user-management',
  UserDetail: '/user-management/user-detail/:id',
  UserDetailManagement: '/user-management/user-detail',
  PropertyManagement: '/property-management',
  UserWallet: '/user-wallet',
  RolesManagement: '/roles-management',
  RolesDetail: '/roles-management/roles-detail/:id',
  RolesDetailWithoutId: '/roles-management/roles-detail',
  viewSubAdmin: '/roles-management/sub-admin',
  editSubAdmin: '/roles-management/sub-admin/edit-subadmin/:id',
  editSubAdminWithoutId: '/roles-management/sub-admin/edit-subadmin',
  RolesAddSubAdmin: '/roles-management/sub-admin/add-subadmin',
  addNewRole: '/roles-management/add-role',
  editRole: '/roles-management/edit-role/:id',
  editRoleWIthoutId: '/roles-management/edit-role',
  RolesSubAdminDetail: '/roles-management/sub-admin/subadmin-detail/:id',
  RolesSubAdminDetailWithoutId: '/roles-management/sub-admin/subadmin-detail',
  PropertyWallet: '/property-wallet',
  SliceWallet: '/slice-wallet',
  // SliceWalletTransactionDetail: '/slice-wallet/transaction-detail',
  ExternalAccount: '/external-account',
  ExternalAddAccount: '/external-account/add-account',
  ExternalEditAccount: '/external-account/edit-account',
  ExternalViewTypes: '/external-account/view-type',
  ExternalAccountDetail: '/external-account/account-detail/:id',
  ExternalAccountDetailManagement: '/external-account/account-detail',
  CouponManagement: '/coupon-management',
  AddCouponManagement: '/coupon-management/add-coupon',
  ReferralCouponDetail: '/coupon-management/referral-coupon-detail',
  PromotionManagement: '/coupon-management/promotion',
  CMSManagement: '/cms-management',
  AddJustSliceManagement: '/cms-management/add-just-slice-thing',
  EditJustSliceManagement: '/cms-management/edit-just-slice-thing',
  EditJustSliceManagementDetails: '/cms-management/edit-just-slice-thing/:id',
  JustSliceDetailManagement: '/cms-management/just-slice-detail',
  JustSliceDetailManagementDetail: '/cms-management/just-slice-detail/:id',
  AddBlog: '/cms-management/add-blog',
  DailyDoseBlog: '/cms-management/daily-dose',
  EditBlog: '/cms-management/edit-blog',
  EditBlogManagement: '/cms-management/edit-blog/:id',
  EditDailyDose: '/cms-management/edit-daily-dose',
  EditDailyDoseManagement: '/cms-management/edit-daily-dose/:id',
  BlogDetail: '/cms-management/blog-detail',
  BlogDetailManagement: '/cms-management/blog-detail/:id',
  AddNews: '/cms-management/add-news',
  NewsDetail: '/cms-management/news-detail',
  EditNews: '/cms-management/edit-news',
  EditNewsManagement: '/cms-management/edit-news/:id',
  NewsDetailManagement: '/cms-management/news-detail/:id',
  SliceAmbassdor: '/cms-management/slice-ambassador',
  AddSliceAmbassdor: '/cms-management/add-slice-ambassador',
  EditSliceAmbassdor: '/cms-management/edit-slice-ambassador',
  EditSliceAmbassdorDetails: '/cms-management/edit-slice-ambassador/:id',
  SliceAmbassdorDetailManagement: '/cms-management/slice-ambassador-detail',
  SliceAmbassdorDetailManagementDetail: '/cms-management/slice-ambassador-detail/:id',
  AddPerkInvestment: '/cms-management/add-perk-investment',
  EditPerkInvestment: '/cms-management/edit-perk-investment',
  EditPerkInvestmentDetail: '/cms-management/edit-perk-investment/:id',
  PerkInvestmentDetailManagement: '/cms-management/perk-investment-detail',
  PerkInvestmentDetailManagementDetails: '/cms-management/perk-investment-detail/:id',
  AddLearnToInvest: '/cms-management/add-learn-to-invest',
  EditLearnToInvest: '/cms-management/edit-learn-to-invest',
  EditLearnToInvestManagement: '/cms-management/edit-learn-to-invest/:id',
  LearnToInvestDetailManagement: '/cms-management/learn-to-invest-detail',
  LearnToInvestDetail: '/cms-management/learn-to-invest-detail/:id',
  AddIcon: '/cms-management/add-icon',
  EditIcon: '/cms-management/edit-icon',
  EditIconManagement: '/cms-management/edit-icon/:id',
  IconDetailManagement: '/cms-management/icon-detail',
  IconDetail: '/cms-management/icon-detail/:id',
  FaqDetailManagement: '/cms-management/faq-detail',
  FaqDetailManagementComp: '/cms-management/faq-detail/:id',
  AddLegalTitle: '/cms-management/add-title',
  AppScreen: '/cms-management/app-screen',
  AddRewardAndGrowMore: '/cms-management/add-reward-growmore',
  EditRewardAndGrowMore: '/cms-management/edit-reward-growmore',
  EditRewardAndGrowMoreDetail: '/cms-management/edit-reward-growmore/:id',
  RewardAndGrowMoreDetailManagement: '/cms-management/reward-growmore-detail',
  RewardAndGrowMoreDetailManagementDetails: '/cms-management/reward-growmore-detail/:id',
  BlockedUsers: '/user-management/blocked-users',
  PublishProperty: '/property-management/publish-property',
  UpcomingProperty: '/property-management/upcoming-property',
  UnpublishProperty: '/property-management/unpublish-property',
  UnpublishedPropertyDetail: '/property-management',
  PublishedPropertyDetail: '/property-management',
  UpcomingPropertyDetail: '/property-management',
  AddProperty: '/property-management/add-property',
  EditProperty: '/property-management/edit-property/:id',
  EditPropertyManagement: '/property-management/edit-property',
  PropertyDetail: '/property-management/:id',
  PropertyDetailManagement: '/property-management',
  KycDetail: '/user-management/user-detail/kyc-detail/:id',
  kycDetails: '/user-management/user-detail/kyc-detail',
  KycProfileDetailHistory: '/user-management/user-detail/kyc-detail/profile-detail-history/:id',
  KycProfileDetailHistorys: '/user-management/user-detail/kyc-detail/profile-detail-history',

  KycIdVerificationHistory: '/user-management/user-detail/kyc-detail/id-verification-history/:id',
  KycIdVerificationHistorys: '/user-management/user-detail/kyc-detail/id-verification-history',

  KycAddressVerificationHistory:
    '/user-management/user-detail/kyc-detail/address-verification-history/:id',
  KycAddressVerificationHistorys:
    '/user-management/user-detail/kyc-detail/address-verification-history',

  AMLCheckHistory: '/user-management/user-detail/kyc-detail/aml-check-history/:id',
  AMLCheckHistorys: '/user-management/user-detail/kyc-detail/aml-check-history',

  UserWalletDetail: '/user-management/user-detail/user-detail-wallet/:id',
  UserWalletDetailManagement: '/user-management/user-detail/user-detail-wallet',
  UserTransactionDetail:
    '/user-management/user-detail/user-detail-wallet/:id/transaction-detail/:transactionId',
  ViewTransaction: '/property-management/view-transaction/:id',
  ViewTransactionProperty: '/property-management/view-transaction',
  ViewTransactionManagement: '/property-management/view-transaction',
  ViewTransactionDetail: '/property-management/transaction-detail/:id',
  ViewTransactionDetails: '/property-wallet/transaction-detail',
  userWalletTransactionDetail: '/user-wallet/transaction-detail/:id',
  userWalletTransactionDetailManagement: '/user-wallet/transaction-detail',
  propertyWalletTransactionDetail: '/property-wallet/transaction-detail/:id',
  TransactionDetail: '/property-management/view-transaction/transaction-detail/:id',
  PropertyTransactionDetail:
    '/property-management/view-transaction/:id/transaction-detail/:transactionId',
  distributeDividendPropertWallet: '/property-wallet/distribute-dividend',
  distributeDividendPropertyManagementWallet: '/property-management/distribute-dividend/:id',
  distributeDividendWithoutPropertyManagementWallet: '/property-management/distribute-dividend',
  finalSettlementPropertyWallet: '/property-wallet/final-settlement',
  finalSettlementPropertyManagementWallet: '/property-management/final-settlement/:id',
  finalSettlementWithoutIdPropertyManagementWallet: '/property-management/final-settlement',
  promotionDetails: '/coupon-management/promotion/details',
  promotionDetailsWithId: '/coupon-management/promotion/details/:id',
  referralDetail: '/coupon-management/referral/details',
  referralDetailWithId: '/coupon-management/referral/details/:id',
  AddCouponManagementReferral: '/coupon-management/referral/add-coupon',
  sliceWalletTransactionDetails: '/slice-wallet/transaction-detail/:id',
  sliceWalletTransactionDetail: '/slice-wallet/transaction-detail',
  pageNotFound: '/page-not-found',
};
export default PathName;
